### PR TITLE
fixes #31. send all java files in the project to javac, so it has the…

### LINKED ISSUE #31: In packages with multiple files, only the current file is sent to javac. Errors are reported if dependencies exist..
If you have multiple files in a package (e.g. FooServer.java and FooResource.java) and one depends on the other, javac will report errors because the other file wasn't provided to it via linter-javac and so it isn't aware of that source.

### PR DESCRIPTION
**Pull request by m4tty**
… source needed to resolve internal type dependencies

### CODE REVIEW

**Comment by kepler0** [comment]
Sorry this is pretty late...

The code looks good. Have you tested this yourself?

**Comment by steelbrain** [comment]
Just a side note that this package is doing too much sync operations, keeping in mind that the renderer process is also responsible for drawing minimap and managing other packages and then doing sync operations is a bad idea IMO. How about we do this asyncly, yes it will get a bit complicated but it's worth the benefits IMO.

**Comment by m4tty** [comment]
@kepler0 no worries. yes, I've been running it locally. I haven't hit any issues.

**Comment by kepler0** [comment]
I'll publish soon.

**Pull request merged**
