### PR TITLE
fix the regex match problem on non-english os

### PR DESCRIPTION
**Pull request by luoch**
fix the regex match problem on non-english os

### CODE REVIEW

**Comment by k2b6s9j** [comment]
Is this still a problem?

**Comment by daw42** [comment]
I'm not sure.  However, at this stage it would be difficult to integrate since it is out of date with respect to the latest master branch.

**Comment by steelbrain** [comment]
Be advised that this PR has some merge conflicts

**Comment by k2b6s9j** [comment]
Seeing as the repository this is based from has been deleted, I'm going to close this.

**Pull request closed without merging**
