### PR TITLE
Release 1.6.0

### LINKED ISSUE #58: Cant figure out the proper configuration
No matter what I try I receive this error.  I have tried moving my JDK to a path thats shorter assuming it was the path length.  Any one have a clue what might be the issue here? 

This is the error thrown everytime I save a java file.  Below is the lines of the coffee script.  I'm fairly certine it has something to do with my javac path but nothing I try seems to work.

```
Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (C:\Users\ghamlett\AppData\Local\atom\app-1.4.1\resources\app.asar\src\buffered-process.js:188:44)
    at new BufferedProcess (C:\Users\ghamlett\AppData\Local\atom\app-1.4.1\resources\app.asar\src\buffered-process.js:50:14)
    at C:\Users\ghamlett\.atom\packages\linter-javac\node_modules\atom-linter\lib\helpers.js:86:81
    at _exec (C:\Users\ghamlett\.atom\packages\linter-javac\node_modules\atom-linter\lib\helpers.js:60:10)
    at Object.exec (C:\Users\ghamlett\.atom\packages\linter-javac\node_modules\atom-linter\lib\helpers.js:134:10)
    at file:///C:/Users/ghamlett/.atom/packages/linter-javac/lib/init.coffee:69:19
    at process._tickCallback (node.js:368:9)
```

init.coffee : lines 67-71
          # Execute javac
          helpers.exec(@javaExecutablePath, args, {stream: 'stderr', cwd: wd})
            .then (val) =>
              @parse(val, textEditor)

### PR DESCRIPTION
**Pull request by florianb**
This release
- implements #55 by implementing basic-specs.
- solves #35 by adding the new configuration-setting `Additional Javac Options` which allow custom options to be set.
- solves #65 and adds a more detailed description in the configuration-settings.
- fixes #58 by cutting of sourcefiles which are too much for your current platform. This is just a quick fix and will be resolved within the next major release.

### CODE REVIEW

**Comment by steelbrain** [comment]
Nice :+1:

**Comment by florianb** [comment]
@steelbrain thanks - with your help! :beers:

How may i support the Changelog-generation? Are all commits in master recognized, or only the tagged ones?

**Comment by steelbrain** [comment]
We don't usually write commits in changelog, we instead write the changes we feel significant even if they are covered in several commits

**Comment by florianb** [comment]
So i'd supposed to foster the changelog by hand, right?

**Comment by steelbrain** [comment]
Yep

**Comment by steelbrain** [comment]
Another alternative technique @Arcanemagus has been using recently is to mention PRs in changelog instead of commits

**Comment by florianb** [comment]
Aye - thanks again! :beers:

**Comment by Arcanemagus** [comment]
On the ones I manually write at least, most of them are just being generated by the tool liked at the bottom of them.

**Pull request merged**
